os: linux
arch: arm64
dist: xenial
language: python
cache: pip
notifications:
  email: change

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

env:
  global:
    - INSTALL_TYPE="setup"
    - CHECK_TYPE="test"
    - OPTIONAL_DEPENDS=

before_install:
  - travis_retry tools/install_dependencies.sh

install:
  - travis_retry tools/install_package.sh

script:
  - tools/run_checks.sh

after_success:
  - travis_retry python -m pip install codecov
