name: netneurotools
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.6
    - flake8
    - matplotlib
    - mayavi
    - nibabel
    - nilearn
    - numba
    - "numpy>=1.16"
    - pandas
    - pip
    - "pytest>=3.6"
    - pytest-cov
    - scikit-learn
    - "scipy>1.4.0"
    - "sphinx>=1.2"
    - sphinx-gallery
    - sphinx_rtd_theme
    - versioneer
    - pip:
        - git+https://github.com/aestrivex/bctpy.git#egg=bctpy
        - pysurfer
